README.md

Signed-off-by: Ce Gao <ce.gao@outlook.com>

feat: Add some new projects

---

README.md

Signed-off-by: Ce Gao <ce.gao@outlook.com>

feat: Add more projects

---

README.md

1. Added relatively novel category for ML applications- ie Data & Feature enrichment
2. Added a link to a Python library for that category
3. Updated a ToC

Data enrichment tools for machine learning as a new category

---

README.md

Adding OpenOps dashboard under visualization.

Adding openops

---

README.md

fix: Add envd

---

README.md
scripts/github-markdown-toc

fix: Add some new projects

---

README.md

fix: Add vector search

---

README.md

feat: Add awesome lists

---

README.md

fix: Add automl

---

README.md

feat: Add fedml

---

README.md

chore: Add LLMOps

---

README.md

Hello!
I have added some awesome projects to the list, such as:
- ML Platform
- [ModelFox](https://github.com/modelfoxdotdev/modelfox)
- [Primehub](https://github.com/InfuseAI/primehub)
- Data Management
- [ArtiVC](https://github.com/InfuseAI/ArtiVC)
And add a new category:
- Data Tracking
- [Piperider](https://github.com/InfuseAI/piperider)
Thanks for taking the time to review this; I hope you have an excellent new year!

feat: Add some project

---

README.md

Signed-off-by: NeroHin [q56105014@gs.ncku.edu.tw](mailto:q56105014@gs.ncku.edu.tw)
Hello!
I have added some awesome projects to the list, such as:
ML Serving Frameworks
[Cortex](https://www.cortex.dev/)
Workflow
[Prefect](https://github.com/PrefectHQ/prefect) 
[Airflow](https://airflow.apache.org/)
Data Management
[Delta-Lake](https://github.com/delta-io/delta)
[Pachyderm](https://github.com/pachyderm/pachyderm)
Federated ML
[Harmonia](https://github.com/ailabstw/harmonia)
Thanks for taking the time to review this.

feat: Add some new project

---

README.md

Signed-off-by: NeroHin [q56105014@gs.ncku.edu.tw](mailto:q56105014@gs.ncku.edu.tw)
Hello!
I have added some projects to the list, such as:
Workflow
[VDP](https://github.com/instill-ai/vdp)
Data Tracking
[LUX](https://github.com/lux-org/lux)
Thanks for taking the time to review this.

feat: add LUX and VDP

---

README.md

Signed-off-by: NeroHin [q56105014@gs.ncku.edu.tw](mailto:q56105014@gs.ncku.edu.tw)
Hello!
I have added some projects to the list, such as:
Data/Feature enrichment
[Feast](https://github.com/feast-dev/feast)
Model Management
[MLEM](https://github.com/iterative/mlem)
ML Platforms
[MLRun](https://github.com/mlrun/mlrun)
AutoML
[Pycaret](https://github.com/pycaret/pycaret)
Thanks for taking the time to review this.

feat: add pycaret, MLRun, MLEM and Feast

---

README.md

Add LlamaIndex (GPT Index)

---

README.md

feat: add xTuring

---

README.md

This is to make the readme more clear (focus on LLMOps)

chore: Refine the layout and add code AI

---

README.md

Hello!
I have added some projects to the list, such as:
LLM
[GLM-6B (ChatGLM)](https://github.com/THUDM/ChatGLM-6B)
[BELLE](https://github.com/LianjiaTech/BELLE)
[Luotuo](https://github.com/LC1332/Luotuo-Chinese-LLM)
Large Model Serving 
[Flowise](https://github.com/FlowiseAI/Flowise)
Foundation Model Fine Tuning
[p-tuning-v2](https://github.com/THUDM/P-tuning-v2)
Thanks for taking the time to review this.

feat: add LLM, Large Model Serving and Foundation Model Fine Tuning

---

README.md

Hello! Creator of lanarky here! 👋 
Would be great if you can add my library to this list.
Lanarky is a FastAPI framework to build production-grade LLM applications.
https://github.com/ajndkr/lanarky
- 📝 added lanarky reference to README

chore: add Lanarky under "Frameworks/Servers for Serving"

---

README.md

Hamilton has a few applications for LLMs -- meant to make it easier to build pipelines/dataflows that are easy to read and debug. Can also build out serving pipelines, and has some visibility/data quality capabilities.

Adds Hamilton to workflow section

---

README.md

Added new LLMOps platform (agenta)

Added agenta in LLMOps category

---

README.md

Great initiative you have going here! 🚀 
I'm adding Giskard's python package under the observability section. It's a framework that detects risks of biases, performance issues and errors in 4 lines of code.

Add Giskard to observability section

---

README.md

Update README.md with inference engines

---

README.md

I think this looks a bit nicer and is easier to scan read (as the descriptions / names are better aligned). Thoughts?

Format sections as tables and update badge style

---

README.md

Adds Vellum Search to the list of options in the Search section.

Add Vellum to Search Section

---

README.md

GPUStack, an open-source GPU cluster manager for running and managing LLMs.
https://github.com/gpustack/gpustack

Add GPUStack to LLMOps

---

README.md

Hey, would be great to add gotoHuman to the list

Incl. gotoHuman

---

README.md

Add Latest Huggingface Library and fix some 'Not found repo' errors

Add Latest Huggingface Library and fix some 'Not found repo' errors
